### ISSUE TITLE
Review pre-made CMS options

### ISSUE THREAD

**Issue by johnrees** [wikihouseproject/wikihouse.cc#16]
## static

- [ ] https://www.datocms.com
- [ ] https://www.contentful.com

## dynamic (rails)

- [ ] https://github.com/denkGroot/Spina
- [ ] https://github.com/refinery/refinerycms
- [ ] http://www.pushtype.org
- [ ] https://github.com/sferik/rails_admin

**Comment by jonleighton** [comment]
OK, I've had a look and a think. Here's what I think of the options:

**Static**

I really like this concept for statically-generated sites, but the wikihouse site is not one of those. On reflection it probably doesn't make sense for it to become one, either, because:

* There's already some dynamic stuff going on
* There's likely to be more in the future
* The Rails app already exists

We *could* plug these systems into a Rails app, but I think it would add more complication (what happens if their service goes down, do we implement caching of the data?)

**Dynamic**

I'm most interested in systems which are more like frameworks than a pre-built CMS, since we want to build out the data model ourselves rather than just having a way for non-techies to create pages on a site.

In that vein, my thinking was to go with [Rails Admin](https://github.com/sferik/rails_admin) which seems fine and flexible enough for our purposes but its UX isn't going to win any design awards.

I hadn't already come across [PushType](http://www.pushtype.org/) but it looks very nice and much more user friendly than Rails Admin. It also scores points for being more of a framework - we can define what types of things need to be editable, what fields they have, etc.

PushType looks quite new so I think there's a bit of a risk that we might encounter lots of problems along the way. It looks like it's being actively developed though and a community is starting to form.

My feeling is to try out PushType and see how it goes, but if we encounter significant issues along the way then be ready to fall back to Rails Admin.

**Comment by johnrees** [comment]
PushType it is then! Thanks for the overview.
