### ISSUE TITLE
Re-enable CSRF protection

### ISSUE THREAD

**Issue by jonleighton** [wikihouseproject/wikihouse.cc#30]
This should be a prerequisite to deploying the CMS functionality in order to maintain the security of the admin section.

From @johnrees:

> you'll see csrf is disabled in application_controller, this was a temporary measure because of it causing problems with the pjax page loading (it's not using turbolinks because of the way the pages load in - flying up from the bottom to replace previous content)

**Comment by johnrees** [comment]
OK IIRC the issue was with the enquiry forms not submitting, due to the CSRF not always being replaced correctly after an partial page replacement/load https://github.com/wikihouseproject/wikihouse.cc/blob/master/vendor/assets/javascripts/pjax.js#L251

(related https://github.com/wikihouseproject/wikihouse.cc/issues/8)

I just did a precursory check and things seem to work with it in place now, but I'll try and find time to check properly later today so it can be reenabled asap.

**Comment by johnrees** [comment]
Done
